### ISSUE TITLE
One model with different indexes or different models?

### ISSUE THREAD

**Issue by elfeffe** [algolia/algoliasearch-laravel#122]
I have a set of items that belongs to different websites, some items belongs to website xx and some others to website yy.
I'm not sure if it's better to have all the items in the same laravel model, or if it's better to have different models, since I need separated indexes for them.
Algolia updates indexes when the model is updated, but how to specify a subset inside the model (xx and yy)?

**Comment by maxiloc** [comment]
Hi @elfeffe 

It mostly depends on the UI/UX you want to provide. if you want a single list of results it's better in one index otherwise if you want to display several section it's better to have several.

In case you want to go with one index you need to implement the `getAlgoliaRecord` on your model:

```
public function getAlgoliaRecord()
    {
        return array_merge($this->toArray(), [
            'subset' => $this->getSubset()
        ]);
    }
```

Also when updating an element in the subset you will need to trigger manually the reindex of the "parent" element.

Does that makes sense ?

**Comment by julienbourdeau** [comment]
Hi @elfeffe,

I hope Maxime answered your questions. If you have any further question feel free to update this thread.
