### ISSUE TITLE
Ensure we're supporting Laravel 4

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-laravel#33]

**Comment by vinkla** [comment]
Do we really need to?

**Comment by redox** [comment]
Not yet sure but we got several times the question in the past few days. Even if simple to upgrade from 4 to 5, I understand it can heavy for some users. You think it's a lot of work @vinkla? Our Rails plugin targets multiple major releases without too much effort, is that something doable with Laravel? Is it common to have 1 version per major version (in that case, is it 1 or N github repositories?)?

**Comment by vinkla** [comment]
The problem is that your current releases points against Laravel 5+ and it means that future versions will point against a downgraded versionen of Laravel. Which could cause some problems. For starter, you won't be able to use my Algolia package since it only supports Laravel 5 and above.

IMO if it is necessary to support Laravel 4 I think you should create a separate package. You'll need to create a custom Algolia manager and update the provider class to support Laravel 4. Other than that I think most of the other stuff should work fine. I don't think it would take that long to build since you already have most of the classes in this repository.
