### ISSUE TITLE
Date condition not working 

### ISSUE THREAD

**Issue by hamog** [algolia/algoliasearch-laravel#92]
Hi, This code works correctly in Laravel
```PHP
Post::where('created_at', '>', $date)->get()
```
but happen error in Alogolia search 
```PHP
Post::search($request->search)->where('created_at', '>', $date)->get()
```
And error message:
AlgoliaSearch\AlgoliaException with message 'Invalid syntax for numeric condition:created_at=>'

**Comment by JanPetr** [comment]
Hello @hamog,
sorry for the very late answer.

The `search()` method of your model takes as second parameter array of parameters for search. You can see the list of off all parameters in [Algolia documentation](https://www.algolia.com/doc/api-client/php/search/#search-parameters).

So if you want filter your results according the date, it might look like this:
```php
$result = Post::search('search query', ['filters' => 'date > 1234']);
```

Be careful as the `date` has to be numerical. So the best way is to store a timestamp instead of the date.
